### ISSUE TITLE
Did something change?

### ISSUE THREAD

**Issue by minakhan01** [firebase/polymerfire#116] opened 2016-09-14 16:33 UTC
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by morganchen12** [comment] 2016-09-14 16:54
accidental dupe of #117

**Closed** 2016-09-14 16:54 UTC
